export const POST_ORDER_ERROR = 'POST_ORDER_ERROR';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const REMOVE_ORDER_MODAL_ITEM = 'REMOVE_ORDER_MODAL_ITEM';